# Generated by Django 5.2.17 on 2026-09-07 23:58

import django.db.models.deletion
import parking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=220)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('nation', models.CharField(choices=[('england', 'England'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('northern_ireland', 'Northern Ireland')], max_length=24)),
                ('local_authority', models.CharField(max_length=160)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('parking_type', models.CharField(choices=[('car_park', 'Car park'), ('multi_storey', 'Multi-storey'), ('on_street', 'On-street parking')], default='car_park', max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=160)),
                ('spaces_total', models.PositiveIntegerField(blank=True, null=True)),
                ('disabled_spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('tariff_info', models.TextField(blank=True, help_text='Price information. Official records use the current council/NPP tariff.')),
                ('charging_times', models.CharField(blank=True, max_length=220)),
                ('restrictions', models.TextField(blank=True)),
                ('payment_info', models.CharField(blank=True, max_length=220)),
                ('payment_location_code', models.CharField(blank=True, max_length=40)),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True, max_length=700, validators=[parking.models.validate_official_source])),
                ('council_verified', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image_source_url', models.URLField(blank=True, max_length=1000)),
                ('image_credit', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_favourites', to=settings.AUTH_USER_MODEL)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='parking.parkinglocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Spaces available'), ('busy', 'Busy / nearly full'), ('full', 'Full')], max_length=20)),
                ('spaces_available', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reports', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='parking.parkinglocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['nation', 'local_authority'], name='parking_par_nation_a_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['latitude', 'longitude'], name='parking_par_latitud_idx'),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'parking'), name='unique_user_parking_favourite'),
        ),
    ]
